name: build-unitTest-uiTest
on: [pull_request]
jobs:
  kotlin:
    name: build / unitTest / uiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: ./gradlew :app:assembleRelease
      - name: UnitTest
        run: ./gradlew :app:testReleaseUnitTest
      - name: UiTest
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck