name: unitTest
on: [pull_request]
jobs:
  kotlin:
    name: unitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: UnitTest
        run: ./gradlew :app:testReleaseUnitTest